### PR TITLE
Fixed compilation errors

### PR DESCRIPTION
**Pull request by komodovaran**
* Updated requirements with pip freeze --all
* Fixed import error
* Fixed readme

### CODE REVIEW

**Comment by komodovaran** [comment]
After a bit of back and forth it's finally working on MacOS 10.15.5.
